 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"Ettercap", "ettercap-pkexec -G", "/usr/share/pixmaps/ettercap.svg" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-unstable.png" },
     {"Google Earth", "/opt/google/earth/free/google-earth ", "/usr/share/icons/hicolor/16x16/apps/google-earth.png" },
     {"Pidgin 互联网通讯程序", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share/icons/gnome/16x16/devices/computer.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"bcloud", "bcloud-gui", "/usr/share/icons/hicolor/16x16/apps/bcloud.png" },
     {"xmradio", "xmradio", "/usr/share/icons/hicolor/16x16/apps/xmradio.png" },
     {"豆瓣FM", "doubanfm-qt", "///usr/share/pixmaps/QDoubanFM.png" },
     {"远程桌面查看器", "vinagre ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
     {"阿里旺旺", "AliWangWang", "/usr/share/pixmaps/AliWangWang.png" },
 }

 local menudb53804b7d726967c58fcc8c9ca03d27 = {
     {"Foxit Reader", "foxitreader ", "/usr/share/pixmaps/foxitreader.png" },
     {"HomeBank", "homebank ", "/usr/share/icons/hicolor/16x16/apps/homebank.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Planner", "planner ", "/usr/share/pixmaps/gnome-planner.png" },
     {"ReText", "retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"XMind", "/usr/share/xmind/XMind", "/usr/share/pixmaps/xmind.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
 }

 local menue1b7cee794666669f55acead93513971 = {
     {"Agave", "agave", "/usr/share/icons/hicolor/16x16/apps/agave.png" },
     {"Dia 图表编辑器", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"Feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU 图像处理程序", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Scribus", "scribus ", "///usr/share/scribus/icons/scribus.png" },
     {"Tiled", "tiled", "/usr/share/icons/hicolor/16x16/apps/tiled.png" },
     {"Viewnior", "viewnior ", "/usr/share/icons/hicolor/16x16/apps/viewnior.png" },
     {"图像查看器", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

 local menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {
     {"Adobe Flash Player", "flashplayer", "/usr/share/icons/hicolor/16x16/apps/flash.png" },
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"DeaDBeeF", "deadbeef ", "/usr/share/icons/hicolor/16x16/apps/deadbeef.png" },
     {"GNOME MPlayer", "gnome-mplayer ", "/usr/share/icons/hicolor/16x16/apps/gnome-mplayer.png" },
     {"Gsopcast", "gsopcast", "/usr/share/pixmaps/gsopcast.png" },
     {"KW 音乐", "kwplayer", "/usr/share/icons/hicolor/24x24/apps/kwplayer.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Radio Tray", "radiotray", "/usr/share/pixmaps/radiotray.png" },
     {"gtk-recordMyDesktop", "gtk-recordMyDesktop", "/usr/share/pixmaps/gtk-recordmydesktop.png" },
     {"xmradio", "xmradio", "/usr/share/icons/hicolor/16x16/apps/xmradio.png" },
     {"录音机", "gnome-sound-recorder", "/usr/share/icons/hicolor/16x16/apps/gnome-sound-recorder.png" },
     {"茄子", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
 }

 local menu8640cb1581c2ae2de5a1462405b2943b = {
     {"Cycle", "cycle", "/usr/share/pixmaps/cycle.xpm" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Marble", "marble-qt ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-touch ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-mobile ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
 }

 local menuba08216f13dd1742157412386eee1225 = {
     {"天书棋谈", "gmchess", "/usr/share/pixmaps/gmchess.png" },
 }

 local menude71492af019157e5a5ef958b570e760 = {
     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"File Types Editor", "assogiate", "/usr/share/icons/hicolor/16x16/apps/assogiate.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"NVCLOCK", "nvclock_gtk", "/usr/share/icons/hicolor/48x48/apps/nvclock.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"ROX Filer", "rox", "/usr/share/pixmaps/rox.png" },
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xsensors", "xsensors", "/usr/share/pixmaps/xsensors.png" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"打印机管理", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"文件管理器 PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"配置编辑器", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
 }

 local menu41282bf95e43c64d579757573a03cdde = {
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"GHex", "ghex ", "/usr/share/icons/hicolor/16x16/apps/ghex.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Giggle", "giggle ", "/usr/share/icons/hicolor/16x16/apps/giggle.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Java Mission Control", "/usr/lib/jvm/java-8-jdk/bin/jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java Monitoring and Management Console", "/usr/lib/jvm/java-8-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java VisualVM", "/usr/lib/jvm/java-8-jdk/bin/jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"bpython", "xterm -e /usr/bin/bpython"},
     {"bpython2", "xterm -e /usr/bin/bpython2"},
     {"pgAdmin III", "/usr/bin/pgadmin3", "///usr/share/pgadmin3/pgAdmin3.png" },
 }

 local menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Catfish File Search", "catfish", "/usr/share/pixmaps/catfish.svg" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Gnote", "gnote ", "/usr/share/icons/hicolor/16x16/apps/gnote.png" },
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"Root 终端", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"ScreenRuler", "/usr/bin/screenruler", "///usr/share/pixmaps/screenruler.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xchm", "xchm ", "/usr/share/pixmaps/xchm-48.png" },
     {"Xpad", "xpad"},
     {"bpython", "xterm -e /usr/bin/bpython"},
     {"bpython2", "xterm -e /usr/bin/bpython2"},
     {"compton", "compton"},
     {"gedit", "gedit ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"地图", "gnome-maps", "/usr/share/icons/hicolor/16x16/apps/gnome-maps.png" },
     {"天气", "gapplication launch org.gnome.Weather.Application", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Weather.Application.png" },
     {"字符映射表", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"归档管理器", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"磁盘", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
 }

xdgmenu = {
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"教育", menu8640cb1581c2ae2de5a1462405b2943b},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}

