 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Geary 邮件", "geary ", "/usr/share/icons/hicolor/16x16/apps/geary.svg" },
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Earth", "/opt/google/earth/free/google-earth ", "/usr/share/icons/hicolor/16x16/apps/google-earth.png" },
     {"Mumble", "mumble"},
     {"Pidgin 互联网通讯程序", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"PyBitmessage", "pybitmessage ", "/usr/share/icons/hicolor/24x24/apps/pybitmessage.png" },
     {"PyWebQQ", "pywebqq", "///usr/share/pywebqq/QQ.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"TM2009", "/opt/longene/wineapp/tm2009/tm2009.sh"},
     {"TeamViewer 8", "/opt/teamviewer8/tv_bin/script/teamviewer", "///opt/teamviewer8/tv_bin/desktop/teamviewer.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share/icons/gnome/16x16/devices/computer.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"tdx", "/opt/longene/tdx/tdx.sh", "///opt/longene/tdx/tdx.ico" },
     {"unison", "unison-x11", "/usr/share/pixmaps/unison.png" },
     {"xmradio", "xmradio", "/usr/share/icons/hicolor/16x16/apps/xmradio.png" },
     {"坚果云 ", "sh -c \"nohup /opt/nutstore/bin/nutstore-pydaemon.py >/dev/null 2>&1 &\"", "/usr/share/icons/hicolor/64x64/apps/nutstore.png" },
     {"迅雷(Wine)", "/usr/bin/wine-thunder", "///usr/share/icons/thunder.png" },
     {"远程桌面查看器", "vinagre ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
     {"阿里旺旺", "AliWangWang", "/usr/share/pixmaps/AliWangWang.png" },
 }

 local menudb53804b7d726967c58fcc8c9ca03d27 = {
     {"Geary 邮件", "geary ", "/usr/share/icons/hicolor/16x16/apps/geary.svg" },
     {"Getting Things GNOME!", "gtg ", "/usr/share/icons/hicolor/16x16/apps/gtg.png" },
     {"GnuCash", "gnucash ", "/usr/share/icons/hicolor/16x16/apps/gnucash-icon.png" },
     {"HomeBank", "homebank ", "/usr/share/icons/hicolor/16x16/apps/homebank.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"WPS 文字", "/usr/bin/wps ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wpsmain.png" },
     {"WPS 演示", "/usr/bin/wpp ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wppmain.png" },
     {"WPS 表格", "/usr/bin/et ", "/usr/share/icons/hicolor/48x48/apps/wps-office-etmain.png" },
     {"XMind", "/usr/share/xmind/XMind", "/usr/share/pixmaps/xmind.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"项目管理", "planner ", "/usr/share/pixmaps/gnome-planner.png" },
 }

 local menue1b7cee794666669f55acead93513971 = {
     {"Agave", "agave", "/usr/share/icons/hicolor/16x16/apps/agave.png" },
     {"Blender", "blender", "/usr/share/icons/hicolor/16x16/apps/blender.png" },
     {"Dia 图表编辑器", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"Feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU 图像处理程序", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/pencil/skin/classic/icon.svg" },
     {"Scribus", "scribus ", "///usr/share/scribus/icons/scribus.png" },
     {"Tiled", "tiled", "/usr/share/icons/hicolor/16x16/apps/tiled.png" },
     {"Viewnior", "viewnior ", "/usr/share/icons/hicolor/16x16/apps/viewnior.png" },
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/gthumb.png" },
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
     {"图像查看器", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

 local menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cinelerra ", "cinelerra", "/usr/share/pixmaps/cinelerra.xpm" },
     {"DeaDBeeF", "deadbeef ", "/usr/share/icons/hicolor/16x16/apps/deadbeef.png" },
     {"FreetuxTV", "freetuxtv", "/usr/share/icons/hicolor/16x16/apps/freetuxtv.png" },
     {"GMLive", "gmlive", "/usr/share/pixmaps/gmlive.png" },
     {"GNOME MPlayer", "gnome-mplayer ", "/usr/share/icons/hicolor/16x16/apps/gnome-mplayer.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Rhythmbox", "rhythmbox ", "/usr/share/icons/hicolor/16x16/apps/rhythmbox.png" },
     {"VLC media player", "/usr/bin/vlc ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"XBMC Media Center", "xbmc", "/usr/share/icons/hicolor/48x48/apps/xbmc.png" },
     {"gtk-recordMyDesktop", "gtk-recordMyDesktop", "/usr/share/pixmaps/gtk-recordmydesktop.png" },
     {"xmradio", "xmradio", "/usr/share/icons/hicolor/16x16/apps/xmradio.png" },
     {"录音机", "gnome-sound-recorder", "/usr/share/icons/hicolor/16x16/apps/gnome-sound-recorder.png" },
     {"茄子", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
 }

 local menu8640cb1581c2ae2de5a1462405b2943b = {
     {"Cycle", "cycle", "/usr/share/pixmaps/cycle.xpm" },
     {"GeoGebra", "geogebra ", "/usr/share/icons/hicolor/16x16/apps/geogebra.png" },
     {"Marble", "marble", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
 }

 local menuba08216f13dd1742157412386eee1225 = {
     {"Urban Terror", "urbanterror", "/usr/share/pixmaps/urbanterror.png" },
     {"天书棋谈", "gmchess", "/usr/share/pixmaps/gmchess.png" },
 }

 local menude71492af019157e5a5ef958b570e760 = {
     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"Fcitx (使用轻量界面)", "fcitx -u fcitx-light-ui", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"File Types Editor", "assogiate", "/usr/share/icons/hicolor/16x16/apps/assogiate.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"NVCLOCK", "nvclock_gtk", "/usr/share/icons/hicolor/48x48/apps/nvclock.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"ROX Filer", "rox", "/usr/share/pixmaps/rox.png" },
     {"Thunar 文件管理器", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xsensors", "xsensors", "/usr/share/pixmaps/xsensors.png" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"打印机管理", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"批量重命名", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"终端", "gnome-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"配置编辑器", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
 }

 local menu41282bf95e43c64d579757573a03cdde = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Eclipse", "eclipse"},
     {"GHex", "ghex ", "/usr/share/icons/hicolor/16x16/apps/ghex.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Java Monitoring and Management Console", "jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Java VisualVM", "jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/pencil/skin/classic/icon.svg" },
     {"Pgadmin3", "pgadmin3", "/usr/share/pixmaps/pgadmin3.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "/usr/bin/qtcreator", "///usr/share/icons/hicolor/512x512/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Work Bench", "workbench", "/usr/share/pixmaps/wb.png" },
 }

 local menu3b6fab8ae1a5e1bef9fa2320d64c4c2a = {
     {"Easystroke 鼠标手势辨认", "easystroke"},
 }

 local menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Avant 窗口导航器", "avant-window-navigator", "/usr/share/icons/hicolor/24x24/apps/avant-window-navigator.png" },
     {"Catfish File Search", "catfish", "/usr/share/pixmaps/catfish.svg" },
     {"ChmSee", "chmsee ", "/usr/share/pixmaps/chmsee-icon.png" },
     {"Easystroke 鼠标手势辨认", "easystroke"},
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Gnote", "gnote ", "/usr/share/icons/hicolor/16x16/apps/gnote.png" },
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"Plank", "plank", "/usr/share/icons/hicolor/16x16/apps/plank.svg" },
     {"Root 终端", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"ScreenRuler", "/usr/bin/screenruler", "///usr/share/pixmaps/screenruler.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xchm", "xchm ", "/usr/share/pixmaps/xchm-48.png" },
     {"Xpad", "xpad"},
     {"compton", "compton"},
     {"归档管理器", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"搜索文件...", "gnome-search-tool", "/usr/share/icons/gnome/16x16/actions/system-search.png" },
     {"文件管理器 PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"磁盘", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
 }

xdgmenu = {
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"教育", menu8640cb1581c2ae2de5a1462405b2943b},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"辅助功能", menu3b6fab8ae1a5e1bef9fa2320d64c4c2a},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}

